/* SPDX-License-Identifier: (GPL-2.0-only OR MIT) */
/* Copyright (c) 2026 Hardkernel Co., Ltd. */

#ifndef _DT_BINDINGS_AMLOGIC_S7D_AUDIO_RESET_H
#define _DT_BINDINGS_AMLOGIC_S7D_AUDIO_RESET_H

#define S7D_AUDIO_RESET_PDM		0
#define S7D_AUDIO_RESET_TDMINA		1
#define S7D_AUDIO_RESET_TDMINB		2
#define S7D_AUDIO_RESET_TDMINC		3
#define S7D_AUDIO_RESET_TDMINLB		4
#define S7D_AUDIO_RESET_LOOPBACK		5
#define S7D_AUDIO_RESET_TODDRA		6
#define S7D_AUDIO_RESET_TODDRB		7
#define S7D_AUDIO_RESET_TODDRC		8
#define S7D_AUDIO_RESET_FRDDRA		9
#define S7D_AUDIO_RESET_FRDDRB		10
#define S7D_AUDIO_RESET_FRDDRC		11
#define S7D_AUDIO_RESET_TDMOUTA		12
#define S7D_AUDIO_RESET_TDMOUTB		13
#define S7D_AUDIO_RESET_TDMOUTC		14
#define S7D_AUDIO_RESET_SPDIFOUT		15
#define S7D_AUDIO_RESET_SPDIFOUTB		16
#define S7D_AUDIO_RESET_SPDIFIN		17
#define S7D_AUDIO_RESET_EQDRC		18
#define S7D_AUDIO_RESET_RESAMPLE		19
#define S7D_AUDIO_RESET_DDR_ARB		20
#define S7D_AUDIO_RESET_POWDET		21
#define S7D_AUDIO_RESET_TORAM		22
#define S7D_AUDIO_RESET_TOACODEC		23
#define S7D_AUDIO_RESET_TOHDMITX		24
#define S7D_AUDIO_RESET_CLK_TREE		25
#define S7D_AUDIO_RESET_RESAMPLEB		26
#define S7D_AUDIO_RESET_TOVAD		27
#define S7D_AUDIO_RESET_LOCKER		28
#define S7D_AUDIO_RESET_SPDIFIN_LB		29
#define S7D_AUDIO_RESET_FRATV		30
#define S7D_AUDIO_RESET_FRHDMIRX		31
#define S7D_AUDIO_RESET_FRDDRD		32
#define S7D_AUDIO_RESET_LOCKERB		40

#endif
